apiVersion: v1
kind: Service
metadata:
  name: file-store-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: file-store
  ports:
    - name: http
      port: 9180
      targetPort: http
    - name: public-http
      port: 9182
      targetPort: public-http
    - name: https
      port: 9181
      targetPort: https
