apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speech-api-ingress
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  {{- if .Values.lumenvox.ingress.className }}
  ingressClassName: {{ .Values.lumenvox.ingress.className }}
  {{- end }}
  rules:
    - host: speech-api.{{ .Values.hostnameSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: speech-api-service
                port:
                  number: 80
