apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speech-api-ingress
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      grpc_read_timeout 120s;
      grpc_send_timeout 120s;
      client_body_timeout 120s;
spec:
  {{- if .Values.global.lumenvox.ingress.className }}
  ingressClassName: {{ .Values.global.lumenvox.ingress.className }}
  {{- end }}
  rules:
    - host: speech-api.{{ .Values.global.hostnameSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: speech-api-service
                port:
                  number: 80
  tls:
    - secretName: speech-tls-secret
      hosts:
        - speech-api.{{ .Values.global.hostnameSuffix }}
