apiVersion: v1
kind: Service
metadata:
  name: reporting-api-service
  namespace: {{ default .Release.Namespace .Values.global.defaultNamespace }}
spec:
  selector:
    app: reporting-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      protocol: TCP
      port: 5110
      targetPort: 5110
