apiVersion: v2
name: lumenvox-speech
description: LumenVox Speech Helm chart for Kubernetes
type: application
version: 6.3.0
appVersion: "6.3.0"
home: https://lumenvox.com
annotations:
  artifacthub.io/containsSecurityUpdates: true
  artifacthub.io/images: |
    - name: asr
      image: lumenvox/asr:6.3
    - name: diarization
      image: lumenvox/diarization:6.3
    - name: cloud-init-tools
      image: lumenvox/cloud-init-tools:6.3
    - name: cloud-logging-sidecar
      image: lumenvox/cloud-logging-sidecar:6.3
    - name: grammar
      image: lumenvox/grammar:6.3
    - name: itn
      image: lumenvox/itn:6.3
    - name: lid
      image: lumenvox/lid:6.3
    - name: lumenvox-api
      image: lumenvox/lumenvox-api:6.3
    - name: neural-tts
      image: lumenvox/neural-tts:6.3
    - name: neuron
      image: lumenvox/neuron:6.3
    - name: nlu
      image: lumenvox/nlu:6.3
    - name: reporting-api
      image: lumenvox/reporting-api:6.3
    - name: session
      image: lumenvox/session:6.3
    - name: tts
      image: lumenvox/tts:6.3
    - name: vad
      image: lumenvox/vad:6.3
