apiVersion: v2
name: lumenvox-common
description: LumenVox Common Components Helm chart for Kubernetes
type: application
version: 5.1.0
appVersion: "5.1.0"
home: https://lumenvox.com
annotations:
  artifacthub.io/containsSecurityUpdates: true
  artifacthub.io/images: |
    - name: admin-portal
      image: lumenvox/admin-portal:5.1
    - name: archive
      image: lumenvox/archive:5.1
    - name: binary-storage
      image: lumenvox/storage:5.1
    - name: cloud-init-tools
      image: lumenvox/cloud-init-tools:5.1
    - name: configuration
      image: lumenvox/configuration:5.1
    - name: deployment
      image: lumenvox/deployment:5.1
    - name: deployment-portal
      image: lumenvox/deployment-portal:5.1
    - name: license
      image: lumenvox/license:5.1
    - name: management-api
      image: lumenvox/management-api:5.1
    - name: resource
      image: lumenvox/resource:5.1
