apiVersion: v2
name: lumenvox-common
description: LumenVox Common Components Helm chart for Kubernetes
type: application
version: 7.0.1
appVersion: "7.0.1"
home: https://lumenvox.com
annotations:
  artifacthub.io/containsSecurityUpdates: true
  artifacthub.io/images: |
    - name: admin-portal
      image: lumenvox/admin-portal:7.0
    - name: archive
      image: lumenvox/archive:7.0
    - name: binary-storage
      image: lumenvox/storage:7.0
    - name: cloud-init-tools
      image: lumenvox/cloud-init-tools:7.0
    - name: configuration
      image: lumenvox/configuration:7.0
    - name: deployment
      image: lumenvox/deployment:7.0
    - name: deployment-portal
      image: lumenvox/deployment-portal:7.0
    - name: license
      image: lumenvox/license:7.0
    - name: management-api
      image: lumenvox/management-api:7.0
    - name: resource
      image: lumenvox/resource:7.0
    - name: file-store
      image: lumenvox/file-store:7.0
