apiVersion: v1
kind: Service
metadata:
  name: asr-audio-service
  namespace: {{ default .Release.Namespace .Values.defaultNamespace }}
spec:
  selector:
    app: asr-audio
  ports:
    - name: http
      protocol: TCP
      port: 5110
      targetPort: 5110
    - name: grpc
      protocol: TCP
      port: 5010
      targetPort: 5010
