apiVersion: v2
name: lumenvox-vb
description: LumenVox Voice Biometrics Helm chart for Kubernetes
type: application
version: 3.2.0
appVersion: "3.2.0"
home: https://lumenvox.com

dependencies:
  - name: "prometheus"
    condition: prometheus.enabled
    version: 14.11.1
    repository: "https://prometheus-community.github.io/helm-charts"
